### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by tracerrx** [rs/scanman#1]
Getting the following after following install instructions on Jessie/Pi 3

[INFO   ] [Logger      ] Record log in /root/.kivy/logs/kivy_16-09-29_1.txt
[INFO   ] [Kivy        ] v1.9.2-dev0
[INFO   ] [Python      ] v2.7.9 (default, Sep 17 2016, 20:26:04)
[GCC 4.9.2]
[INFO   ] [Factory     ] 193 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
 Traceback (most recent call last):
   File "/usr/local/bin/scanman", line 9, in <module>
     load_entry_point('scanman==0.8', 'console_scripts', 'scanman')()
   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
     return get_distribution(dist).load_entry_point(group, name)
   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
     return ep.load()
   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
     ['**name**'])
   File "/usr/local/lib/python2.7/dist-packages/scanman/main.py", line 13, in <module>
     from img2pdf import pdfdoc
   File "/usr/local/lib/python2.7/dist-packages/img2pdf.py", line 204
 SyntaxError: Non-ASCII character '\xe2' in file /usr/local/lib/python2.7/dist-packages/img2pdf.py on line 204, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by rs** [comment]
Looks like an error introduced in img2pdf. Are you sure you have the last version of this library?

**Comment by tracerrx** [comment]
yes, even ran "sudo pip install img2pdf --upgrade".  Get the same result, using jessie image dated 09-23-2016.
